import '../models/user_model.dart';
import '../models/shop_model.dart';
import '../models/product_model.dart';
import '../models/post_model.dart';
import '../models/offer_model.dart';
import '../models/lead_model.dart';

class NearoDatabase {
  static final UserModel defaultUser = UserModel(
    id: 'u1',
    name: 'Dikesh Sharma',
    email: 'dikesh.sharma@gmail.com',
    phone: '+91 98765 43210',
    profileImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150',
    location: 'Sector 62, Noida',
    interests: ['Coffee', 'Electronics', 'Fresh Food', 'Fashion'],
    followingShops: ['s1', 's5'],
    savedProducts: ['p2', 'p5'],
    createdAt: DateTime.now().subtract(const Duration(days: 30)),
  );

  static final ShopModel defaultShop = ShopModel(
    id: 's1',
    shopName: 'Aura Coffee',
    ownerName: 'Aman Verma',
    logo: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=100',
    banner: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=600',
    address: 'A-12, Sector 62, Noida',
    latitude: 28.6273,
    longitude: 77.3725,
    rating: 4.8,
    followers: 1240,
    category: 'Cafe',
    isVerified: true,
    phone: '+91 98765 11111',
    whatsapp: '9876511111',
    description: 'Artisanal coffee roasters serving freshly brewed coffee, delicious pastries and premium beans sourced directly from local estates.',
  );

  static final List<ShopModel> initialShops = [
    defaultShop,
    ShopModel(
      id: 's2',
      shopName: 'Green Fresh Mart',
      ownerName: 'Sunita Devi',
      logo: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=100',
      banner: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?w=600',
      address: 'Shop 4, Market Complex, Sector 62, Noida',
      latitude: 28.6295,
      longitude: 77.3750,
      rating: 4.5,
      followers: 850,
      category: 'Groceries',
      isVerified: true,
      phone: '+91 98765 22222',
      whatsapp: '9876522222',
      description: 'Your neighborhood daily store for organic farm-fresh vegetables, seasonal fruits, and dairy products.',
    ),
    ShopModel(
      id: 's3',
      shopName: 'Tech Hub Mobile',
      ownerName: 'Rohan Gupta',
      logo: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=100',
      banner: 'https://images.unsplash.com/photo-1531403009284-440f080d1e12?w=600',
      address: 'F-22, First Floor, Mall of Noida',
      latitude: 28.6240,
      longitude: 77.3710,
      rating: 4.6,
      followers: 2100,
      category: 'Electronics',
      isVerified: true,
      phone: '+91 98765 33333',
      whatsapp: '9876533333',
      description: 'One-stop shop for latest premium smartphones, wireless audio accessories, and repair services.',
    ),
    ShopModel(
      id: 's4',
      shopName: 'Urban Fashion',
      ownerName: 'Vikram Singh',
      logo: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=100',
      banner: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=600',
      address: 'G-10, Block B, Sector 63, Noida',
      latitude: 28.6310,
      longitude: 77.3780,
      rating: 4.2,
      followers: 590,
      category: 'Fashion',
      isVerified: false,
      phone: '+91 98765 44444',
      whatsapp: '9876544444',
      description: 'Minimalist streetwear and essentials curated for the modern aesthetic. Premium fabrics, solid colors.',
    ),
    ShopModel(
      id: 's5',
      shopName: 'Sharma Kirana',
      ownerName: 'Rajesh Sharma',
      logo: 'https://images.unsplash.com/photo-1604719312566-8912e9227c6a?w=100',
      banner: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?w=600',
      address: 'Main Chowk, Sector 62, Noida',
      latitude: 28.6280,
      longitude: 77.3690,
      rating: 4.7,
      followers: 1420,
      category: 'Groceries',
      isVerified: true,
      phone: '+91 98765 55555',
      whatsapp: '9876555555',
      description: 'Serving quality household groceries, spices, and snacks to families for the last 25 years.',
    ),
    ShopModel(
      id: 's6',
      shopName: 'Nearo Electronics',
      ownerName: 'Manish Kumar',
      logo: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=100',
      banner: 'https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=600',
      address: 'Shop 102, electronic Market, Sector 62',
      latitude: 28.6255,
      longitude: 77.3735,
      rating: 4.4,
      followers: 980,
      category: 'Electronics',
      isVerified: true,
      phone: '+91 98765 66666',
      whatsapp: '9876566666',
      description: 'Wholesale and retail of smart devices, kitchen appliances, and customizable speaker systems.',
    ),
    ShopModel(
      id: 's7',
      shopName: 'Royal Bakery',
      ownerName: 'Harish Rawat',
      logo: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=100',
      banner: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600',
      address: 'B-8, Sector 62, Noida',
      latitude: 28.6285,
      longitude: 77.3715,
      rating: 4.9,
      followers: 1650,
      category: 'Cafe',
      isVerified: true,
      phone: '+91 98765 77777',
      whatsapp: '9876577777',
      description: 'Gourmet cakes, fresh sourdough bread, hand-crafted croissants, and celebrations catering.',
    ),
    ShopModel(
      id: 's8',
      shopName: 'Fresh Fruits Market',
      ownerName: 'Karan Mehra',
      logo: 'https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?w=100',
      banner: 'https://images.unsplash.com/photo-1610832958506-ee56336191d1?w=600',
      address: 'Booth 12, Sector 62, Noida',
      latitude: 28.6300,
      longitude: 77.3740,
      rating: 4.3,
      followers: 430,
      category: 'Groceries',
      isVerified: false,
      phone: '+91 98765 88888',
      whatsapp: '9876588888',
      description: 'Imported and local fresh fruits. Mango festivals, apple baskets, and premium fruit platters.',
    ),
  ];

  static final List<ProductModel> initialProducts = [
    ProductModel(
      id: 'p1',
      shopId: 's8',
      name: 'Fresh Mango',
      images: [
        'https://images.unsplash.com/photo-1553279768-865429fa0078?w=500',
        'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?w=500',
      ],
      description: 'Super sweet, handpicked Alphonso mangoes, directly imported from Devgad. Certified carbide-free.',
      price: 120,
      discountPrice: 80, // ₹80/kg
      stock: 50,
      category: 'Groceries',
      likes: 42,
      views: 280,
      createdAt: DateTime.now().subtract(const Duration(days: 2)),
    ),
    ProductModel(
      id: 'p2',
      shopId: 's1',
      name: 'Premium Coffee Beans',
      images: [
        'https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=500',
        'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500',
      ],
      description: 'Single-origin Arabica beans sourced from Chikmagalur, medium roast with notes of chocolate and citrus.',
      price: 599,
      discountPrice: 499, // ₹499
      stock: 20,
      category: 'Cafe',
      likes: 120,
      views: 750,
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
    ProductModel(
      id: 'p3',
      shopId: 's3',
      name: 'Wireless Earbuds',
      images: [
        'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500',
      ],
      description: 'True wireless stereo earbuds with active noise cancellation, 30 hours battery life, and IPX5 rating.',
      price: 1999,
      discountPrice: 999, // ₹999
      stock: 15,
      category: 'Electronics',
      likes: 74,
      views: 640,
      createdAt: DateTime.now().subtract(const Duration(days: 1)),
    ),
    ProductModel(
      id: 'p4',
      shopId: 's2',
      name: 'Organic Tomatoes',
      images: [
        'https://images.unsplash.com/photo-1595855759920-86582396756a?w=500',
      ],
      description: 'Farm fresh red tomatoes grown without synthetic fertilizers. Juicy and perfect for cooking or salads.',
      price: 50,
      discountPrice: 40, // ₹40/kg
      stock: 100,
      category: 'Groceries',
      likes: 12,
      views: 110,
      createdAt: DateTime.now().subtract(const Duration(hours: 12)),
    ),
    ProductModel(
      id: 'p5',
      shopId: 's6',
      name: 'Bluetooth Speaker',
      images: [
        'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500',
      ],
      description: 'Portable waterproof speaker with deep bass, 20W output power, dual drivers, and custom RGB ring.',
      price: 2499,
      discountPrice: 1499, // ₹1499
      stock: 8,
      category: 'Electronics',
      likes: 38,
      views: 310,
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
    ),
    ProductModel(
      id: 'p6',
      shopId: 's7',
      name: 'Chocolate Cake',
      images: [
        'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=500',
      ],
      description: 'Rich Belgian dark chocolate ganache cake, multi-layered, baked fresh daily. Perfect for birthdays.',
      price: 499,
      discountPrice: 399, // ₹399
      stock: 5,
      category: 'Cafe',
      likes: 95,
      views: 520,
      createdAt: DateTime.now().subtract(const Duration(days: 3)),
    ),
    ProductModel(
      id: 'p7',
      shopId: 's4',
      name: 'Fashion T-Shirt',
      images: [
        'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=500',
      ],
      description: '100% organic heavy cotton oversize t-shirt, relaxed fit, pre-shrunk, in classic off-white color.',
      price: 999,
      discountPrice: 599, // ₹599
      stock: 25,
      category: 'Fashion',
      likes: 49,
      views: 390,
      createdAt: DateTime.now().subtract(const Duration(days: 6)),
    ),
    ProductModel(
      id: 'p8',
      shopId: 's7',
      name: 'Fresh Sourdough Bread',
      images: [
        'https://images.unsplash.com/photo-1549931319-a545dcf3bc73?w=500',
      ],
      description: 'Slow fermented classic French sourdough, crisp crust, soft airy crumb, baked in stone deck oven.',
      price: 45,
      discountPrice: 30, // ₹30
      stock: 12,
      category: 'Cafe',
      likes: 27,
      views: 210,
      createdAt: DateTime.now().subtract(const Duration(hours: 6)),
    ),
  ];

  static final List<OfferModel> initialOffers = [
    OfferModel(
      id: 'o1',
      shopId: 's1',
      title: '20% OFF Coffee',
      description: 'Get flat 20% discount on all custom espresso brews and retail bags of single estate beans.',
      discount: '20% OFF',
      expiryDate: DateTime.now().add(const Duration(days: 3)),
      banner: 'https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=500',
    ),
    OfferModel(
      id: 'o2',
      shopId: 's7',
      title: 'Buy 1 Get 1 Burger',
      description: 'Celebrate our bakery burger launch! Buy any signature brioche burger and get another one free.',
      discount: 'BOGO',
      expiryDate: DateTime.now().add(const Duration(days: 2)),
      banner: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500',
    ),
    OfferModel(
      id: 'o3',
      shopId: 's3',
      title: '15% OFF Electronics',
      description: 'Upgrade your audio setup! Enjoy 15% off on all active noise cancelling earbuds and headwear.',
      discount: '15% OFF',
      expiryDate: DateTime.now().add(const Duration(days: 5)),
      banner: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500',
    ),
    OfferModel(
      id: 'o4',
      shopId: 's5',
      title: 'Weekend Grocery Sale',
      description: 'Get extra points and discounts on kitchen pantry staples like pulses, grains, and spices.',
      discount: 'SAVE ₹100',
      expiryDate: DateTime.now().add(const Duration(days: 4)),
      banner: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=500',
    ),
    OfferModel(
      id: 'o5',
      shopId: 's8',
      title: 'Summer Mango Festival',
      description: 'Stock up on sweet mango pulps, crates, and shakes. Special pricing for early hours.',
      discount: 'FESTIVAL',
      expiryDate: DateTime.now().add(const Duration(days: 7)),
      banner: 'https://images.unsplash.com/photo-1601004890684-d8cbf643f5f2?w=500',
    ),
    OfferModel(
      id: 'o6',
      shopId: 's4',
      title: 'Festival Fashion Sale',
      description: 'Complete wardrobe overhaul with discount coupons. Applies to all new items.',
      discount: 'UP TO 30%',
      expiryDate: DateTime.now().add(const Duration(days: 10)),
      banner: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?w=500',
    ),
  ];

  static final List<PostModel> initialPosts = [
    PostModel(
      id: 'post1',
      shopId: 's1',
      type: PostType.offer,
      caption: 'Escape the summer heat with our new Honey Lavender Iced Latte! 🍯💜 Crafted with our house espresso, organic lavender honey syrup, and topped with dried blossoms. Flat 20% discount on coffee today!',
      image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600',
      likes: 85,
      comments: 12,
      createdAt: DateTime.now().subtract(const Duration(hours: 2)),
    ),
    PostModel(
      id: 'post2',
      shopId: 's4',
      type: PostType.product,
      caption: 'Crafted from heavyweight organic cotton. A boxy, retro fit that maintains its structure. The Off-White Vintage Tee is now restocked in sizes S to XXL.',
      image: 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=600',
      likes: 124,
      comments: 25,
      createdAt: DateTime.now().subtract(const Duration(hours: 5)),
    ),
    PostModel(
      id: 'post3',
      shopId: 's7',
      type: PostType.update,
      caption: 'Rise and shine! Fresh sourdough, seeded loaves, and buttery croissants are out of the oven and on the racks. Drop by Aura Bakery for your breakfast fixes!',
      image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=600',
      likes: 45,
      comments: 4,
      createdAt: DateTime.now().subtract(const Duration(hours: 8)),
    ),
  ];

  static final List<LeadModel> initialLeads = [
    LeadModel(
      id: 'l1',
      userId: 'u2',
      userName: 'Rahul Mehra',
      userPhone: '+91 99999 88888',
      productId: 'p2',
      productName: 'Premium Coffee Beans',
      shopId: 's1',
      type: LeadType.whatsappClick,
      status: 'New',
      createdAt: DateTime.now().subtract(const Duration(hours: 1)),
    ),
    LeadModel(
      id: 'l2',
      userId: 'u3',
      userName: 'Sara Khan',
      userPhone: '+91 88888 77777',
      productId: 'p2',
      productName: 'Premium Coffee Beans',
      shopId: 's1',
      type: LeadType.discountRequest,
      status: 'Contacted',
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
    ),
  ];
}
